/**
 * Direct check of the Edge client, outside Netlify.
 *   node --experimental-strip-types scripts/smoke-edge.mts
 * Honours HTTPS_PROXY so it also runs behind a corporate proxy.
 */
import { writeFileSync } from "node:fs";
import { synthesize, listVoices, generateSecMsGec } from "../netlify/functions/_lib/edge-tts.mts";

const proxy = process.env.HTTPS_PROXY ?? process.env.https_proxy;
let agent: unknown;
if (proxy) {
  const { HttpsProxyAgent } = await import("https-proxy-agent");
  agent = new HttpsProxyAgent(proxy);
  console.log("using proxy", proxy);
}

console.log("Sec-MS-GEC:", generateSecMsGec().slice(0, 16), "...");

const started = Date.now();
const result = await synthesize(
  "This audio was generated by a Netlify function, with no Python anywhere in the request path.",
  { voice: "en-US-AriaNeural", boundary: "word", agent },
);
const elapsed = Date.now() - started;

writeFileSync(process.argv[2] ?? "smoke.mp3", result.audio);
console.log(`audio: ${result.audio.length} bytes in ${elapsed}ms`);
console.log(`duration: ${(result.audio.length / 6000).toFixed(2)}s (48 kbps CBR)`);
console.log(`boundaries: ${result.boundaries.length}`);
console.log("first marks:", result.boundaries.slice(0, 4));

const voices = await listVoices();
console.log(`voices: ${voices.length}, e.g.`, voices.find((v) => v.locale === "en-GB"));
